export const YOUTUBE_TRENDING = {
  rock: [
    {
      id: "3JZ4pnNtyxQ",
      title: "Ed Sheeran - Shape of You",
      artist: "Ed Sheeran",
      cover: "https://i.ytimg.com/vi/3JZ4pnNtyxQ/maxresdefault.jpg",
    },
    {
      id: "kJQP7kiw5Fk",
      title: "Luis Fonsi - Despacito ft. Daddy Yankee",
      artist: "Luis Fonsi",
      cover: "https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg",
    },
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      artist: "Wiz Khalifa",
      cover: "https://i.ytimg.com/vi/RgKAFK5djSk/maxresdefault.jpg",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      artist: "Justin Bieber",
      cover: "https://i.ytimg.com/vi/fRh_vgS2dFE/maxresdefault.jpg",
    },
    {
      id: "YykjpeuMNEk",
      title: "Coldplay - Hymn For The Weekend",
      artist: "Coldplay",
      cover: "https://i.ytimg.com/vi/YykjpeuMNEk/maxresdefault.jpg",
    },
    {
      id: "hT_nvWreIhg",
      title: "OneRepublic - Counting Stars",
      artist: "OneRepublic",
      cover: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    },
    {
      id: "YqeW9_5kURI",
      title: "Major Lazer & DJ Snake - Lean On",
      artist: "Major Lazer",
      cover: "https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg",
    },
    {
      id: "pRpeEdMmmQ0",
      title: "Imagine Dragons - Believer",
      artist: "Imagine Dragons",
      cover: "https://i.ytimg.com/vi/pRpeEdMmmQ0/maxresdefault.jpg",
    },
    {
      id: "09R8_2nJtjg",
      title: "Maroon 5 - Sugar",
      artist: "Maroon 5",
      cover: "https://i.ytimg.com/vi/09R8_2nJtjg/maxresdefault.jpg",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      artist: "Mark Ronson",
      cover: "https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg",
    },
  ],
  electronic: [
    {
      id: "YqeW9_5kURI",
      title: "Major Lazer & DJ Snake - Lean On",
      artist: "Major Lazer",
      cover: "https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg",
    },
    {
      id: "YykjpeuMNEk",
      title: "Coldplay - Hymn For The Weekend",
      artist: "Coldplay",
      cover: "https://i.ytimg.com/vi/YykjpeuMNEk/maxresdefault.jpg",
    },
    {
      id: "hT_nvWreIhg",
      title: "OneRepublic - Counting Stars",
      artist: "OneRepublic",
      cover: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    },
    {
      id: "pRpeEdMmmQ0",
      title: "Imagine Dragons - Believer",
      artist: "Imagine Dragons",
      cover: "https://i.ytimg.com/vi/pRpeEdMmmQ0/maxresdefault.jpg",
    },
    {
      id: "09R8_2nJtjg",
      title: "Maroon 5 - Sugar",
      artist: "Maroon 5",
      cover: "https://i.ytimg.com/vi/09R8_2nJtjg/maxresdefault.jpg",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      artist: "Mark Ronson",
      cover: "https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg",
    },
    {
      id: "3JZ4pnNtyxQ",
      title: "Ed Sheeran - Shape of You",
      artist: "Ed Sheeran",
      cover: "https://i.ytimg.com/vi/3JZ4pnNtyxQ/maxresdefault.jpg",
    },
    {
      id: "kJQP7kiw5Fk",
      title: "Luis Fonsi - Despacito ft. Daddy Yankee",
      artist: "Luis Fonsi",
      cover: "https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg",
    },
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      artist: "Wiz Khalifa",
      cover: "https://i.ytimg.com/vi/RgKAFK5djSk/maxresdefault.jpg",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      artist: "Justin Bieber",
      cover: "https://i.ytimg.com/vi/fRh_vgS2dFE/maxresdefault.jpg",
    },
  ],
  jazz: [
    {
      id: "YqeW9_5kURI",
      title: "Major Lazer & DJ Snake - Lean On",
      artist: "Major Lazer",
      cover: "https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg",
    },
    {
      id: "YykjpeuMNEk",
      title: "Coldplay - Hymn For The Weekend",
      artist: "Coldplay",
      cover: "https://i.ytimg.com/vi/YykjpeuMNEk/maxresdefault.jpg",
    },
    {
      id: "hT_nvWreIhg",
      title: "OneRepublic - Counting Stars",
      artist: "OneRepublic",
      cover: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    },
    {
      id: "pRpeEdMmmQ0",
      title: "Imagine Dragons - Believer",
      artist: "Imagine Dragons",
      cover: "https://i.ytimg.com/vi/pRpeEdMmmQ0/maxresdefault.jpg",
    },
    {
      id: "09R8_2nJtjg",
      title: "Maroon 5 - Sugar",
      artist: "Maroon 5",
      cover: "https://i.ytimg.com/vi/09R8_2nJtjg/maxresdefault.jpg",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      artist: "Mark Ronson",
      cover: "https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg",
    },
    {
      id: "3JZ4pnNtyxQ",
      title: "Ed Sheeran - Shape of You",
      artist: "Ed Sheeran",
      cover: "https://i.ytimg.com/vi/3JZ4pnNtyxQ/maxresdefault.jpg",
    },
    {
      id: "kJQP7kiw5Fk",
      title: "Luis Fonsi - Despacito ft. Daddy Yankee",
      artist: "Luis Fonsi",
      cover: "https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg",
    },
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      artist: "Wiz Khalifa",
      cover: "https://i.ytimg.com/vi/RgKAFK5djSk/maxresdefault.jpg",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      artist: "Justin Bieber",
      cover: "https://i.ytimg.com/vi/fRh_vgS2dFE/maxresdefault.jpg",
    },
  ],
  pop: [
    {
      id: "3JZ4pnNtyxQ",
      title: "Ed Sheeran - Shape of You",
      artist: "Ed Sheeran",
      cover: "https://i.ytimg.com/vi/3JZ4pnNtyxQ/maxresdefault.jpg",
    },
    {
      id: "kJQP7kiw5Fk",
      title: "Luis Fonsi - Despacito ft. Daddy Yankee",
      artist: "Luis Fonsi",
      cover: "https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg",
    },
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      artist: "Wiz Khalifa",
      cover: "https://i.ytimg.com/vi/RgKAFK5djSk/maxresdefault.jpg",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      artist: "Justin Bieber",
      cover: "https://i.ytimg.com/vi/fRh_vgS2dFE/maxresdefault.jpg",
    },
    {
      id: "YykjpeuMNEk",
      title: "Coldplay - Hymn For The Weekend",
      artist: "Coldplay",
      cover: "https://i.ytimg.com/vi/YykjpeuMNEk/maxresdefault.jpg",
    },
    {
      id: "hT_nvWreIhg",
      title: "OneRepublic - Counting Stars",
      artist: "OneRepublic",
      cover: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    },
    {
      id: "YqeW9_5kURI",
      title: "Major Lazer & DJ Snake - Lean On",
      artist: "Major Lazer",
      cover: "https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg",
    },
    {
      id: "pRpeEdMmmQ0",
      title: "Imagine Dragons - Believer",
      artist: "Imagine Dragons",
      cover: "https://i.ytimg.com/vi/pRpeEdMmmQ0/maxresdefault.jpg",
    },
    {
      id: "09R8_2nJtjg",
      title: "Maroon 5 - Sugar",
      artist: "Maroon 5",
      cover: "https://i.ytimg.com/vi/09R8_2nJtjg/maxresdefault.jpg",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      artist: "Mark Ronson",
      cover: "https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg",
    },
  ],
  classical: [
    {
      id: "YqeW9_5kURI",
      title: "Major Lazer & DJ Snake - Lean On",
      artist: "Major Lazer",
      cover: "https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg",
    },
    {
      id: "YykjpeuMNEk",
      title: "Coldplay - Hymn For The Weekend",
      artist: "Coldplay",
      cover: "https://i.ytimg.com/vi/YykjpeuMNEk/maxresdefault.jpg",
    },
    {
      id: "hT_nvWreIhg",
      title: "OneRepublic - Counting Stars",
      artist: "OneRepublic",
      cover: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    },
    {
      id: "pRpeEdMmmQ0",
      title: "Imagine Dragons - Believer",
      artist: "Imagine Dragons",
      cover: "https://i.ytimg.com/vi/pRpeEdMmmQ0/maxresdefault.jpg",
    },
    {
      id: "09R8_2nJtjg",
      title: "Maroon 5 - Sugar",
      artist: "Maroon 5",
      cover: "https://i.ytimg.com/vi/09R8_2nJtjg/maxresdefault.jpg",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      artist: "Mark Ronson",
      cover: "https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg",
    },
    {
      id: "3JZ4pnNtyxQ",
      title: "Ed Sheeran - Shape of You",
      artist: "Ed Sheeran",
      cover: "https://i.ytimg.com/vi/3JZ4pnNtyxQ/maxresdefault.jpg",
    },
    {
      id: "kJQP7kiw5Fk",
      title: "Luis Fonsi - Despacito ft. Daddy Yankee",
      artist: "Luis Fonsi",
      cover: "https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg",
    },
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      artist: "Wiz Khalifa",
      cover: "https://i.ytimg.com/vi/RgKAFK5djSk/maxresdefault.jpg",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      artist: "Justin Bieber",
      cover: "https://i.ytimg.com/vi/fRh_vgS2dFE/maxresdefault.jpg",
    },
  ],
  hiphop: [
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      artist: "Wiz Khalifa",
      cover: "https://i.ytimg.com/vi/RgKAFK5djSk/maxresdefault.jpg",
    },
    {
      id: "YqeW9_5kURI",
      title: "Major Lazer & DJ Snake - Lean On",
      artist: "Major Lazer",
      cover: "https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg",
    },
    {
      id: "YykjpeuMNEk",
      title: "Coldplay - Hymn For The Weekend",
      artist: "Coldplay",
      cover: "https://i.ytimg.com/vi/YykjpeuMNEk/maxresdefault.jpg",
    },
    {
      id: "hT_nvWreIhg",
      title: "OneRepublic - Counting Stars",
      artist: "OneRepublic",
      cover: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    },
    {
      id: "pRpeEdMmmQ0",
      title: "Imagine Dragons - Believer",
      artist: "Imagine Dragons",
      cover: "https://i.ytimg.com/vi/pRpeEdMmmQ0/maxresdefault.jpg",
    },
    {
      id: "09R8_2nJtjg",
      title: "Maroon 5 - Sugar",
      artist: "Maroon 5",
      cover: "https://i.ytimg.com/vi/09R8_2nJtjg/maxresdefault.jpg",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      artist: "Mark Ronson",
      cover: "https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg",
    },
    {
      id: "3JZ4pnNtyxQ",
      title: "Ed Sheeran - Shape of You",
      artist: "Ed Sheeran",
      cover: "https://i.ytimg.com/vi/3JZ4pnNtyxQ/maxresdefault.jpg",
    },
    {
      id: "kJQP7kiw5Fk",
      title: "Luis Fonsi - Despacito ft. Daddy Yankee",
      artist: "Luis Fonsi",
      cover: "https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      artist: "Justin Bieber",
      cover: "https://i.ytimg.com/vi/fRh_vgS2dFE/maxresdefault.jpg",
    },
  ],
  ambient: [
    {
      id: "YqeW9_5kURI",
      title: "Major Lazer & DJ Snake - Lean On",
      artist: "Major Lazer",
      cover: "https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg",
    },
    {
      id: "YykjpeuMNEk",
      title: "Coldplay - Hymn For The Weekend",
      artist: "Coldplay",
      cover: "https://i.ytimg.com/vi/YykjpeuMNEk/maxresdefault.jpg",
    },
    {
      id: "hT_nvWreIhg",
      title: "OneRepublic - Counting Stars",
      artist: "OneRepublic",
      cover: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    },
    {
      id: "pRpeEdMmmQ0",
      title: "Imagine Dragons - Believer",
      artist: "Imagine Dragons",
      cover: "https://i.ytimg.com/vi/pRpeEdMmmQ0/maxresdefault.jpg",
    },
    {
      id: "09R8_2nJtjg",
      title: "Maroon 5 - Sugar",
      artist: "Maroon 5",
      cover: "https://i.ytimg.com/vi/09R8_2nJtjg/maxresdefault.jpg",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      artist: "Mark Ronson",
      cover: "https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg",
    },
    {
      id: "3JZ4pnNtyxQ",
      title: "Ed Sheeran - Shape of You",
      artist: "Ed Sheeran",
      cover: "https://i.ytimg.com/vi/3JZ4pnNtyxQ/maxresdefault.jpg",
    },
    {
      id: "kJQP7kiw5Fk",
      title: "Luis Fonsi - Despacito ft. Daddy Yankee",
      artist: "Luis Fonsi",
      cover: "https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg",
    },
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      artist: "Wiz Khalifa",
      cover: "https://i.ytimg.com/vi/RgKAFK5djSk/maxresdefault.jpg",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      artist: "Justin Bieber",
      cover: "https://i.ytimg.com/vi/fRh_vgS2dFE/maxresdefault.jpg",
    },
  ],
  folk: [
    {
      id: "YqeW9_5kURI",
      title: "Major Lazer & DJ Snake - Lean On",
      artist: "Major Lazer",
      cover: "https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg",
    },
    {
      id: "YykjpeuMNEk",
      title: "Coldplay - Hymn For The Weekend",
      artist: "Coldplay",
      cover: "https://i.ytimg.com/vi/YykjpeuMNEk/maxresdefault.jpg",
    },
    {
      id: "hT_nvWreIhg",
      title: "OneRepublic - Counting Stars",
      artist: "OneRepublic",
      cover: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    },
    {
      id: "pRpeEdMmmQ0",
      title: "Imagine Dragons - Believer",
      artist: "Imagine Dragons",
      cover: "https://i.ytimg.com/vi/pRpeEdMmmQ0/maxresdefault.jpg",
    },
    {
      id: "09R8_2nJtjg",
      title: "Maroon 5 - Sugar",
      artist: "Maroon 5",
      cover: "https://i.ytimg.com/vi/09R8_2nJtjg/maxresdefault.jpg",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      artist: "Mark Ronson",
      cover: "https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg",
    },
    {
      id: "3JZ4pnNtyxQ",
      title: "Ed Sheeran - Shape of You",
      artist: "Ed Sheeran",
      cover: "https://i.ytimg.com/vi/3JZ4pnNtyxQ/maxresdefault.jpg",
    },
    {
      id: "kJQP7kiw5Fk",
      title: "Luis Fonsi - Despacito ft. Daddy Yankee",
      artist: "Luis Fonsi",
      cover: "https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg",
    },
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      artist: "Wiz Khalifa",
      cover: "https://i.ytimg.com/vi/RgKAFK5djSk/maxresdefault.jpg",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      artist: "Justin Bieber",
      cover: "https://i.ytimg.com/vi/fRh_vgS2dFE/maxresdefault.jpg",
    },
  ],
};
